### MCP ###
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=500
quarkus.mcp.server.sse.root-path=/mcp

### OAuth2 ###
quarkus.http.auth.permission.authenticated.paths=/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.tenant-paths=/mcp/*
quarkus.oidc.token.audience=quarkus-mcp-staticmap
quarkus.oidc.resource-metadata.enabled=true
quarkus.oidc.resource-metadata.resource=/mcp
quarkus.oidc.resource-metadata.force-https-scheme=false

### Keycloak ###
quarkus.keycloak.devservices.realm-path=staticmap-realm.json
quarkus.keycloak.devservices.realm-name=staticmap
quarkus.keycloak.devservices.create-client=false

### CORS configuration ###
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:6274

### Buckets ##
staticmap.bucketname=staticmap-bucket